zookeeper:
  build: ./zookeeper
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888

postgres:
  build: ./postgres
  ports:
    - 5432:5432
  environment:
    POSTGRES_USER: eventuate
    POSTGRES_PASSWORD: eventuate