version: '3'
services:
  zookeeper:
    build: ./zookeeper
    ports:
      - 2181:2181

  mssql:
    build:
      context: ./mssql/
    image: eventuateio/eventuate-mssql:${DOCKER_IMAGE_TAG:-latest}
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: Eventuate123!
      ACCEPT_EULA: Y
