zookeeper:
  build: ./zookeeper
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888

mssql:
  build: ./mssql
  ports:
    - 1433:1433
  environment:
    SA_PASSWORD: Eventuate123!
    ACCEPT_EULA: Y
