zookeeper:
  build: ./zookeeper
  ports:
    - 2181:2181

mariadb:
  build: ./mariadb
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_USER=mysqluser
    - MYSQL_PASSWORD=mysqlpw
