version: '3'
services:
  zookeeper:
    build:
      context: ./zookeeper/
    image: eventuateio/eventuate-zookeeper:${DOCKER_IMAGE_TAG:-latest}
    ports:
      - 2181:2181

  mysql:
    build:
      context: ./mysql/
    image: eventuateio/eventuate-mysql:${DOCKER_IMAGE_TAG:-latest}
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw