version: '3'
services:
  zookeeper:
    build: ./zookeeper
    ports:
      - 2181:2181

  postgres:
    build:
      context: ./postgres/
    image: eventuateio/eventuate-postgres:${DOCKER_IMAGE_TAG:-latest}
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: eventuate
      POSTGRES_PASSWORD: eventuate