zookeeper:
  build: ./zookeeper
  ports:
    - 2181:2181

postgres:
  build: ./postgres
  ports:
    - 5432:5432
  environment:
    POSTGRES_USER: eventuate
    POSTGRES_PASSWORD: eventuate
    USE_DB_ID: ${USE_DB_ID}
    USE_JSON_PAYLOAD_AND_HEADERS: ${USE_JSON_PAYLOAD_AND_HEADERS}