version: '3'
services:
  zookeeper:
    build: ./zookeeper
    ports:
      - 2181:2181

  mariadb:
    build:
      context: ./mariadb/
    image: eventuateio/eventuate-mariadb:${DOCKER_IMAGE_TAG:-latest}
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
