version: '3'
services:
  zookeeper:
    build: ./zookeeper
    ports:
      - 2181:2181

  mssql:
    build: ./mssql
    image: eventuateio/eventuate-mssql:$DOCKER_IMAGE_TAG
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: Eventuate123!
      ACCEPT_EULA: Y
      USE_DB_ID: ${USE_DB_ID}
      USE_JSON_PAYLOAD_AND_HEADERS: ${USE_JSON_PAYLOAD_AND_HEADERS}