version: 2
jobs:
  build:
    machine: true
    working_directory: ~/eventuate-common
    steps:
      - checkout
      - restore_cache:
          key: eventuate-common-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./gradlew testClasses
      - save_cache:
          paths:
            - ~/.gradle
          key: eventuate-common-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./build-and-test-all.sh
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
  publish:
    machine: true
    working_directory: ~/eventuate-common
    steps:
      - checkout
      - restore_cache:
          key: eventuate-common-{{ checksum "build.gradle" }}
      - run: TERM=dumb ./gradlew testClasses
      - save_cache:
          paths:
            - ~/.gradle
          key: eventuate-common-{{ checksum "build.gradle" }}
      - run:
          name: Publish artifacts
          command: |
            TERM=dumb ./deploy-artifacts.sh
          when: on_success
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - publish:
          requires:
            - build
